# Generated by Django 3.1.7 on 2021-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20210224_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
